// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6mvDSGKIrltGom5kBnSIqYTE44y4oKRE',
    appId: '1:985781218614:web:c18eed98a44714bfccd797',
    messagingSenderId: '985781218614',
    projectId: 'video-chat-demo-550da',
    authDomain: 'video-chat-demo-550da.firebaseapp.com',
    storageBucket: 'video-chat-demo-550da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp-1HicciZNKNbYTf2AzW3rJgVcewm5sk',
    appId: '1:985781218614:android:01af43d245a30052ccd797',
    messagingSenderId: '985781218614',
    projectId: 'video-chat-demo-550da',
    storageBucket: 'video-chat-demo-550da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM25pPnLoCLMotXbDQnxNvYPUc-PNz-eU',
    appId: '1:985781218614:ios:0252bd1fd5062dccccd797',
    messagingSenderId: '985781218614',
    projectId: 'video-chat-demo-550da',
    storageBucket: 'video-chat-demo-550da.appspot.com',
    iosBundleId: 'com.example.realTimeVideoCallsAppZegocloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM25pPnLoCLMotXbDQnxNvYPUc-PNz-eU',
    appId: '1:985781218614:ios:0252bd1fd5062dccccd797',
    messagingSenderId: '985781218614',
    projectId: 'video-chat-demo-550da',
    storageBucket: 'video-chat-demo-550da.appspot.com',
    iosBundleId: 'com.example.realTimeVideoCallsAppZegocloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6mvDSGKIrltGom5kBnSIqYTE44y4oKRE',
    appId: '1:985781218614:web:2a256240825215dfccd797',
    messagingSenderId: '985781218614',
    projectId: 'video-chat-demo-550da',
    authDomain: 'video-chat-demo-550da.firebaseapp.com',
    storageBucket: 'video-chat-demo-550da.appspot.com',
  );
}
